# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import GameManager, GameLoop

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 310, 1101, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(390, 330, 171, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.activeName = QtWidgets.QLabel(self.frame)
        self.activeName.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.activeName.setObjectName("activeName")
        self.activeHP = QtWidgets.QLabel(self.frame)
        self.activeHP.setGeometry(QtCore.QRect(110, 0, 55, 16))
        self.activeHP.setObjectName("activeHP")
        self.activeAttach = QtWidgets.QListView(self.frame)
        self.activeAttach.setGeometry(QtCore.QRect(10, 40, 141, 61))
        self.activeAttach.setObjectName("activeAttach")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 350, 61, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.prize1 = QtWidgets.QLabel(self.frame_2)
        self.prize1.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize1.setObjectName("prize1")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(960, 590, 120, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.discardList = QtWidgets.QListView(self.frame_3)
        self.discardList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.discardList.setObjectName("discardList")
        self.discardlbl = QtWidgets.QLabel(self.frame_3)
        self.discardlbl.setGeometry(QtCore.QRect(40, 0, 55, 16))
        self.discardlbl.setObjectName("discardlbl")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(150, 490, 120, 161))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bench1Name = QtWidgets.QLabel(self.frame_5)
        self.bench1Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench1Name.setObjectName("bench1Name")
        self.bench1HP = QtWidgets.QLabel(self.frame_5)
        self.bench1HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench1HP.setObjectName("bench1HP")
        self.bench1Attach = QtWidgets.QListWidget(self.frame_5)
        self.bench1Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench1Attach.setObjectName("bench1Attach")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(390, 490, 120, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.bench3Name = QtWidgets.QLabel(self.frame_6)
        self.bench3Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.bench3Name.setObjectName("bench3Name")
        self.bench3HP = QtWidgets.QLabel(self.frame_6)
        self.bench3HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.bench3HP.setObjectName("bench3HP")
        self.bench3Attach = QtWidgets.QListWidget(self.frame_6)
        self.bench3Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench3Attach.setObjectName("bench3Attach")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(270, 490, 120, 161))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.bench2Name = QtWidgets.QLabel(self.frame_7)
        self.bench2Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.bench2Name.setObjectName("bench2Name")
        self.bench2HP = QtWidgets.QLabel(self.frame_7)
        self.bench2HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.bench2HP.setObjectName("bench2HP")
        self.bench2Attach = QtWidgets.QListWidget(self.frame_7)
        self.bench2Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench2Attach.setObjectName("bench2Attach")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(510, 490, 120, 161))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.bench4Name = QtWidgets.QLabel(self.frame_8)
        self.bench4Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench4Name.setObjectName("bench4Name")
        self.bench4HP = QtWidgets.QLabel(self.frame_8)
        self.bench4HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench4HP.setObjectName("bench4HP")
        self.bench4Attach = QtWidgets.QListWidget(self.frame_8)
        self.bench4Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench4Attach.setObjectName("bench4Attach")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(630, 490, 120, 161))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.bench5Name = QtWidgets.QLabel(self.frame_9)
        self.bench5Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench5Name.setObjectName("bench5Name")
        self.bench5HP = QtWidgets.QLabel(self.frame_9)
        self.bench5HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench5HP.setObjectName("bench5HP")
        self.bench5Attach = QtWidgets.QListWidget(self.frame_9)
        self.bench5Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench5Attach.setObjectName("bench5Attach")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(960, 350, 120, 221))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.deckList = QtWidgets.QListView(self.frame_4)
        self.deckList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.deckList.setObjectName("deckList")
        self.decklbl = QtWidgets.QLabel(self.frame_4)
        self.decklbl.setGeometry(QtCore.QRect(50, 0, 55, 16))
        self.decklbl.setObjectName("decklbl")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(70, 350, 61, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.prize2 = QtWidgets.QLabel(self.frame_10)
        self.prize2.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize2.setObjectName("prize2")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(10, 430, 61, 80))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.prize3 = QtWidgets.QLabel(self.frame_11)
        self.prize3.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize3.setObjectName("prize3")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setGeometry(QtCore.QRect(70, 430, 61, 80))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.prize4 = QtWidgets.QLabel(self.frame_12)
        self.prize4.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize4.setObjectName("prize4")
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setGeometry(QtCore.QRect(10, 510, 61, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.prize5 = QtWidgets.QLabel(self.frame_13)
        self.prize5.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize5.setObjectName("prize5")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(70, 510, 61, 80))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.prize6 = QtWidgets.QLabel(self.frame_14)
        self.prize6.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize6.setObjectName("prize6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activeName.setText(_translate("MainWindow", "Active Name"))
        self.activeHP.setText(_translate("MainWindow", "HP"))
        self.prize1.setText(_translate("MainWindow", "TextLabel"))
        self.discardlbl.setText(_translate("MainWindow", "Discard"))
        self.bench1Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench1HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench3Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench3HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench2Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench2HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench4Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench4HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench5Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench5HP.setText(_translate("MainWindow", "TextLabel"))
        self.decklbl.setText(_translate("MainWindow", "Deck"))
        self.prize2.setText(_translate("MainWindow", "TextLabel"))
        self.prize3.setText(_translate("MainWindow", "TextLabel"))
        self.prize4.setText(_translate("MainWindow", "TextLabel"))
        self.prize5.setText(_translate("MainWindow", "TextLabel"))
        self.prize6.setText(_translate("MainWindow", "TextLabel"))

    def setActive(self):
        
        self.activeName.setText(GameManager.Gameboard.playerActive[0].Name)
        self.activeHP.setText(str(GameManager.Gameboard.playerActive[0].Hp))

    def setBench(self):
        if len(GameManager.Gameboard.playerBench) >= 1:
            self.bench1Name.setText(GameManager.Gameboard.playerBench[0].Name)
            self.bench1HP.setText(str(GameManager.Gameboard.playerBench[0].Hp))
        if len(GameManager.Gameboard.playerBench) >= 2:
            self.bench2Name.setText(GameManager.Gameboard.playerBench[1].Name)
            self.bench2HP.setText(str(GameManager.Gameboard.playerBench[1].Hp))
        if len(GameManager.Gameboard.playerBench) >= 3:
            self.bench3Name.setText(GameManager.Gameboard.playerBench[2].Name)
            self.bench3HP.setText(str(GameManager.Gameboard.playerBench[2].Hp))
        if len(GameManager.Gameboard.playerBench) >= 4:
            self.bench4Name.setText(GameManager.Gameboard.playerBench[3].Name)
            self.bench4HP.setText(str(GameManager.Gameboard.playerBench[3].Hp))
        if len(GameManager.Gameboard.playerBench) == 5:
            self.bench5Name.setText(GameManager.Gameboard.playerBench[4].Name)
            self.bench5HP.setText(str(GameManager.Gameboard.playerBench[4].Hp))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    GameLoop.GameLoop()
    ui.setActive()
    ui.setBench()
    MainWindow.show()
    sys.exit(app.exec_())

