# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import GameManager
import GameLoop

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 1036)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 520, 1221, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(410, 560, 171, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.activeName = QtWidgets.QLabel(self.frame)
        self.activeName.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.activeName.setObjectName("activeName")
        self.activeHP = QtWidgets.QLabel(self.frame)
        self.activeHP.setGeometry(QtCore.QRect(110, 0, 55, 16))
        self.activeHP.setObjectName("activeHP")
        self.activeAttach = QtWidgets.QListView(self.frame)
        self.activeAttach.setGeometry(QtCore.QRect(10, 40, 141, 61))
        self.activeAttach.setObjectName("activeAttach")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 560, 61, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.prize1 = QtWidgets.QLabel(self.frame_2)
        self.prize1.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize1.setObjectName("prize1")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(980, 780, 120, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.discardList = QtWidgets.QListView(self.frame_3)
        self.discardList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.discardList.setObjectName("discardList")
        self.discardlbl = QtWidgets.QLabel(self.frame_3)
        self.discardlbl.setGeometry(QtCore.QRect(40, 0, 55, 16))
        self.discardlbl.setObjectName("discardlbl")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(170, 700, 120, 161))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bench1Name = QtWidgets.QLabel(self.frame_5)
        self.bench1Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench1Name.setObjectName("bench1Name")
        self.bench1HP = QtWidgets.QLabel(self.frame_5)
        self.bench1HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench1HP.setObjectName("bench1HP")
        self.bench1Attach = QtWidgets.QListWidget(self.frame_5)
        self.bench1Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench1Attach.setObjectName("bench1Attach")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(410, 700, 120, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.bench3Name = QtWidgets.QLabel(self.frame_6)
        self.bench3Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.bench3Name.setObjectName("bench3Name")
        self.bench3HP = QtWidgets.QLabel(self.frame_6)
        self.bench3HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.bench3HP.setObjectName("bench3HP")
        self.bench3Attach = QtWidgets.QListWidget(self.frame_6)
        self.bench3Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench3Attach.setObjectName("bench3Attach")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(290, 700, 120, 161))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.bench2Name = QtWidgets.QLabel(self.frame_7)
        self.bench2Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.bench2Name.setObjectName("bench2Name")
        self.bench2HP = QtWidgets.QLabel(self.frame_7)
        self.bench2HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.bench2HP.setObjectName("bench2HP")
        self.bench2Attach = QtWidgets.QListWidget(self.frame_7)
        self.bench2Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench2Attach.setObjectName("bench2Attach")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(530, 700, 120, 161))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.bench4Name = QtWidgets.QLabel(self.frame_8)
        self.bench4Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench4Name.setObjectName("bench4Name")
        self.bench4HP = QtWidgets.QLabel(self.frame_8)
        self.bench4HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench4HP.setObjectName("bench4HP")
        self.bench4Attach = QtWidgets.QListWidget(self.frame_8)
        self.bench4Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench4Attach.setObjectName("bench4Attach")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(650, 700, 120, 161))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.bench5Name = QtWidgets.QLabel(self.frame_9)
        self.bench5Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.bench5Name.setObjectName("bench5Name")
        self.bench5HP = QtWidgets.QLabel(self.frame_9)
        self.bench5HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.bench5HP.setObjectName("bench5HP")
        self.bench5Attach = QtWidgets.QListWidget(self.frame_9)
        self.bench5Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.bench5Attach.setObjectName("bench5Attach")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(980, 540, 120, 221))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.deckList = QtWidgets.QListView(self.frame_4)
        self.deckList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.deckList.setObjectName("deckList")
        self.decklbl = QtWidgets.QLabel(self.frame_4)
        self.decklbl.setGeometry(QtCore.QRect(50, 0, 55, 16))
        self.decklbl.setObjectName("decklbl")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(60, 560, 61, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.prize2 = QtWidgets.QLabel(self.frame_10)
        self.prize2.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize2.setObjectName("prize2")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(0, 640, 61, 80))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.prize3 = QtWidgets.QLabel(self.frame_11)
        self.prize3.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize3.setObjectName("prize3")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setGeometry(QtCore.QRect(60, 640, 61, 80))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.prize4 = QtWidgets.QLabel(self.frame_12)
        self.prize4.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize4.setObjectName("prize4")
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setGeometry(QtCore.QRect(0, 720, 61, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.prize5 = QtWidgets.QLabel(self.frame_13)
        self.prize5.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize5.setObjectName("prize5")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(60, 720, 61, 80))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.prize6 = QtWidgets.QLabel(self.frame_14)
        self.prize6.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.prize6.setObjectName("prize6")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(1020, 120, 61, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.oppprize4 = QtWidgets.QLabel(self.frame_15)
        self.oppprize4.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize4.setObjectName("oppprize4")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(960, 120, 61, 80))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.oppprize3 = QtWidgets.QLabel(self.frame_16)
        self.oppprize3.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize3.setObjectName("oppprize3")
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setGeometry(QtCore.QRect(1020, 40, 61, 80))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.oppprize2 = QtWidgets.QLabel(self.frame_17)
        self.oppprize2.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize2.setObjectName("oppprize2")
        self.frame_18 = QtWidgets.QFrame(self.centralwidget)
        self.frame_18.setGeometry(QtCore.QRect(960, 40, 61, 80))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.oppprize1 = QtWidgets.QLabel(self.frame_18)
        self.oppprize1.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize1.setObjectName("oppprize1")
        self.frame_19 = QtWidgets.QFrame(self.centralwidget)
        self.frame_19.setGeometry(QtCore.QRect(1020, 200, 61, 80))
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.oppprize6 = QtWidgets.QLabel(self.frame_19)
        self.oppprize6.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize6.setObjectName("oppprize6")
        self.frame_20 = QtWidgets.QFrame(self.centralwidget)
        self.frame_20.setGeometry(QtCore.QRect(960, 200, 61, 80))
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.oppprize5 = QtWidgets.QLabel(self.frame_20)
        self.oppprize5.setGeometry(QtCore.QRect(0, 30, 55, 16))
        self.oppprize5.setObjectName("oppprize5")
        self.frame_21 = QtWidgets.QFrame(self.centralwidget)
        self.frame_21.setGeometry(QtCore.QRect(10, 20, 120, 221))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.oppdeckList = QtWidgets.QListView(self.frame_21)
        self.oppdeckList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.oppdeckList.setObjectName("oppdeckList")
        self.decklbl_2 = QtWidgets.QLabel(self.frame_21)
        self.decklbl_2.setGeometry(QtCore.QRect(50, 0, 55, 16))
        self.decklbl_2.setObjectName("decklbl_2")
        self.frame_22 = QtWidgets.QFrame(self.centralwidget)
        self.frame_22.setGeometry(QtCore.QRect(10, 260, 120, 221))
        self.frame_22.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.oppdiscardList = QtWidgets.QListView(self.frame_22)
        self.oppdiscardList.setGeometry(QtCore.QRect(10, 20, 101, 191))
        self.oppdiscardList.setObjectName("oppdiscardList")
        self.discardlbl_2 = QtWidgets.QLabel(self.frame_22)
        self.discardlbl_2.setGeometry(QtCore.QRect(40, 0, 55, 16))
        self.discardlbl_2.setObjectName("discardlbl_2")
        self.frame_23 = QtWidgets.QFrame(self.centralwidget)
        self.frame_23.setGeometry(QtCore.QRect(360, 220, 120, 161))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.oppbench2Name = QtWidgets.QLabel(self.frame_23)
        self.oppbench2Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.oppbench2Name.setObjectName("oppbench2Name")
        self.oppbench2HP = QtWidgets.QLabel(self.frame_23)
        self.oppbench2HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.oppbench2HP.setObjectName("oppbench2HP")
        self.oppbench2Attach = QtWidgets.QListWidget(self.frame_23)
        self.oppbench2Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.oppbench2Attach.setObjectName("oppbench2Attach")
        self.frame_24 = QtWidgets.QFrame(self.centralwidget)
        self.frame_24.setGeometry(QtCore.QRect(420, 400, 171, 111))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.oppactiveName = QtWidgets.QLabel(self.frame_24)
        self.oppactiveName.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.oppactiveName.setObjectName("oppactiveName")
        self.oppactiveHP = QtWidgets.QLabel(self.frame_24)
        self.oppactiveHP.setGeometry(QtCore.QRect(110, 0, 55, 16))
        self.oppactiveHP.setObjectName("oppactiveHP")
        self.oppactiveAttach_2 = QtWidgets.QListView(self.frame_24)
        self.oppactiveAttach_2.setGeometry(QtCore.QRect(10, 40, 141, 61))
        self.oppactiveAttach_2.setObjectName("oppactiveAttach_2")
        self.frame_25 = QtWidgets.QFrame(self.centralwidget)
        self.frame_25.setGeometry(QtCore.QRect(600, 220, 120, 161))
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.oppbench4Name = QtWidgets.QLabel(self.frame_25)
        self.oppbench4Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.oppbench4Name.setObjectName("oppbench4Name")
        self.oppbench4HP_2 = QtWidgets.QLabel(self.frame_25)
        self.oppbench4HP_2.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.oppbench4HP_2.setObjectName("oppbench4HP_2")
        self.oppbench4Attach = QtWidgets.QListWidget(self.frame_25)
        self.oppbench4Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.oppbench4Attach.setObjectName("oppbench4Attach")
        self.frame_26 = QtWidgets.QFrame(self.centralwidget)
        self.frame_26.setGeometry(QtCore.QRect(480, 220, 120, 161))
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.oppbench3Name = QtWidgets.QLabel(self.frame_26)
        self.oppbench3Name.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.oppbench3Name.setObjectName("oppbench3Name")
        self.oppbench3HP = QtWidgets.QLabel(self.frame_26)
        self.oppbench3HP.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.oppbench3HP.setObjectName("oppbench3HP")
        self.oppbench3Attach = QtWidgets.QListWidget(self.frame_26)
        self.oppbench3Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.oppbench3Attach.setObjectName("oppbench3Attach")
        self.frame_27 = QtWidgets.QFrame(self.centralwidget)
        self.frame_27.setGeometry(QtCore.QRect(720, 220, 120, 161))
        self.frame_27.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.oppbench5Name = QtWidgets.QLabel(self.frame_27)
        self.oppbench5Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.oppbench5Name.setObjectName("oppbench5Name")
        self.oppbench5HP = QtWidgets.QLabel(self.frame_27)
        self.oppbench5HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.oppbench5HP.setObjectName("oppbench5HP")
        self.oppbench5Attach = QtWidgets.QListWidget(self.frame_27)
        self.oppbench5Attach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.oppbench5Attach.setObjectName("oppbench5Attach")
        self.frame_28 = QtWidgets.QFrame(self.centralwidget)
        self.frame_28.setGeometry(QtCore.QRect(240, 220, 120, 161))
        self.frame_28.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.oppbench1Name = QtWidgets.QLabel(self.frame_28)
        self.oppbench1Name.setGeometry(QtCore.QRect(40, 20, 55, 16))
        self.oppbench1Name.setObjectName("oppbench1Name")
        self.oppbench1HP = QtWidgets.QLabel(self.frame_28)
        self.oppbench1HP.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.oppbench1HP.setObjectName("oppbench1HP")
        self.oppAttach = QtWidgets.QListWidget(self.frame_28)
        self.oppAttach.setGeometry(QtCore.QRect(10, 70, 101, 81))
        self.oppAttach.setObjectName("oppAttach")
        self.atkButton = QtWidgets.QPushButton(self.centralwidget)
        self.atkButton.setGeometry(QtCore.QRect(840, 560, 93, 28))
        self.atkButton.setObjectName("atkButton")
        self.retreatButton = QtWidgets.QPushButton(self.centralwidget)
        self.retreatButton.setGeometry(QtCore.QRect(840, 600, 93, 28))
        self.retreatButton.setObjectName("retreatButton")
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(840, 640, 93, 28))
        self.endButton.setObjectName("endButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activeName.setText(_translate("MainWindow", "Active Name"))
        self.activeHP.setText(_translate("MainWindow", "HP"))
        self.prize1.setText(_translate("MainWindow", "TextLabel"))
        self.discardlbl.setText(_translate("MainWindow", "Discard"))
        self.bench1Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench1HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench3Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench3HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench2Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench2HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench4Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench4HP.setText(_translate("MainWindow", "TextLabel"))
        self.bench5Name.setText(_translate("MainWindow", "TextLabel"))
        self.bench5HP.setText(_translate("MainWindow", "TextLabel"))
        self.decklbl.setText(_translate("MainWindow", "Deck"))
        self.prize2.setText(_translate("MainWindow", "TextLabel"))
        self.prize3.setText(_translate("MainWindow", "TextLabel"))
        self.prize4.setText(_translate("MainWindow", "TextLabel"))
        self.prize5.setText(_translate("MainWindow", "TextLabel"))
        self.prize6.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize4.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize3.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize2.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize1.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize6.setText(_translate("MainWindow", "TextLabel"))
        self.oppprize5.setText(_translate("MainWindow", "TextLabel"))
        self.decklbl_2.setText(_translate("MainWindow", "Deck"))
        self.discardlbl_2.setText(_translate("MainWindow", "Discard"))
        self.oppbench2Name.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench2HP.setText(_translate("MainWindow", "TextLabel"))
        self.oppactiveName.setText(_translate("MainWindow", "Active Name"))
        self.oppactiveHP.setText(_translate("MainWindow", "HP"))
        self.oppbench4Name.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench4HP_2.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench3Name.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench3HP.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench5Name.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench5HP.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench1Name.setText(_translate("MainWindow", "TextLabel"))
        self.oppbench1HP.setText(_translate("MainWindow", "TextLabel"))
        self.atkButton.setText(_translate("MainWindow", "Attack"))
        self.retreatButton.setText(_translate("MainWindow", "Retreat"))
        self.endButton.setText(_translate("MainWindow", "End"))

        
    def setActive(self):
        
        self.activeName.setText(GameManager.Gameboard.playerActive[0].Name)
        self.activeHP.setText(str(GameManager.Gameboard.playerActive[0].Hp))
        self.oppactiveName.setText(GameManager.Gameboard.oppActive[0].Name)
        self.oppactiveHP.setText(str(GameManager.Gameboard.oppActive[0].Hp))

    def setBench(self):
        if len(GameManager.Gameboard.playerBench) >= 1:
            self.bench1Name.setText(GameManager.Gameboard.playerBench[0].Name)
            self.bench1HP.setText(str(GameManager.Gameboard.playerBench[0].Hp))
        if len(GameManager.Gameboard.playerBench) >= 2:
            self.bench2Name.setText(GameManager.Gameboard.playerBench[1].Name)
            self.bench2HP.setText(str(GameManager.Gameboard.playerBench[1].Hp))
        if len(GameManager.Gameboard.playerBench) >= 3:
            self.bench3Name.setText(GameManager.Gameboard.playerBench[2].Name)
            self.bench3HP.setText(str(GameManager.Gameboard.playerBench[2].Hp))
        if len(GameManager.Gameboard.playerBench) >= 4:
            self.bench4Name.setText(GameManager.Gameboard.playerBench[3].Name)
            self.bench4HP.setText(str(GameManager.Gameboard.playerBench[3].Hp))
        if len(GameManager.Gameboard.playerBench) == 5:
            self.bench5Name.setText(GameManager.Gameboard.playerBench[4].Name)
            self.bench5HP.setText(str(GameManager.Gameboard.playerBench[4].Hp))

    def setPrize(self):
        self.prize1.setText(GameManager.Gameboard.playerPrize[0].Name)
        self.prize2.setText(GameManager.Gameboard.playerPrize[1].Name)
        self.prize3.setText(GameManager.Gameboard.playerPrize[2].Name)
        self.prize4.setText(GameManager.Gameboard.playerPrize[3].Name)
        self.prize5.setText(GameManager.Gameboard.playerPrize[4].Name)
        self.prize6.setText(GameManager.Gameboard.playerPrize[5].Name)
        self.oppprize1.setText(GameManager.Gameboard.oppPrize[0].Name)
        self.oppprize2.setText(GameManager.Gameboard.oppPrize[1].Name)
        self.oppprize3.setText(GameManager.Gameboard.oppPrize[2].Name)
        self.oppprize4.setText(GameManager.Gameboard.oppPrize[3].Name)
        self.oppprize5.setText(GameManager.Gameboard.oppPrize[4].Name)
        self.oppprize6.setText(GameManager.Gameboard.oppPrize[5].Name)

    def setDiscard(self):
        model = QtGui.QStandardItemModel()
        self.discardList.setModel(model)
        for i in range(len(GameManager.Gameboard.playerDiscard)):
            model.appendRow(QtGui.QStandardItem(GameManager.Gameboard.playerDiscard[i].Name))

        model2 = QtGui.QStandardItemModel()
        self.oppdiscardList.setModel(model2)
        for i in range(len(GameManager.Gameboard.oppDiscard)):
            model2.appendRow(QtGui.QStandardItem(GameManager.Gameboard.oppDiscard[i].Name))
        
    def setDeck(self):
        model = QtGui.QStandardItemModel()
        self.deckList.setModel(model)
        for i in range(len(GameManager.Gameboard.playerDeck)):
            model.appendRow(QtGui.QStandardItem(GameManager.Gameboard.playerDeck[i].Name))

        model2 = QtGui.QStandardItemModel()
        self.oppdeckList.setModel(model2)
        for i in range(len(GameManager.Gameboard.oppDeck)):
            model2.appendRow(QtGui.QStandardItem(GameManager.Gameboard.oppDeck[i].Name))

    def setActiveAttached(self):
        model = QtGui.QStandardItemModel()
        self.activeAttach.setModel(model)
        for i in range(len(GameManager.Gameboard.playerActive[0].Energies)):
            model.appendRow(QtGui.QStandardItem(GameManager.Gameboard.playerActive[0].Energies[i].Name))
        for i in range(len(GameManager.Gameboard.playerActive[0].Tools)):
            model.appendRow(QtGui.QStandardItem(GameManager.Gameboard.playerActive[0].Tools[i].Name))        
    def create():
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
    def attack(self, test):
        test.attack()
        self.setActive()

if __name__ == "__main__":
    #import sys
    #app = QtWidgets.QApplication(sys.argv)
    #MainWindow = QtWidgets.QMainWindow()
    #ui = Ui_MainWindow()
    #ui.setupUi(MainWindow)
    GameLoop.GameLoop()
    end = False
    
    
##    ui.setActive()
##    ui.setBench()
##    ui.setPrize()
##    ui.setDiscard()
##    ui.setDeck()
##    ui.setActiveAttached()
    
    
    #MainWindow.show()
    #sys.exit(app.exec_())

    
